"use client";

import type { TimelineEntry } from "@/types";
import { formatDate } from "@/lib/utils";

interface CICDTimelineProps {
  timeline: TimelineEntry[];
  retryLimit: number;
}

interface IterationBlock {
  iteration: number;
  status: "PASSED" | "FAILED";
  timestamp: string;
  events: TimelineEntry[];
}

function extractIterations(timeline: TimelineEntry[]): IterationBlock[] {
  const blocks: IterationBlock[] = [];
  let current: TimelineEntry[] = [];
  let iterationNum = 0;

  for (const entry of timeline) {
    if (entry.event === "ITERATION_START") {
      if (current.length > 0 && iterationNum > 0) {
        const hasPassed = current.some(
          (e) => e.event === "CI_PASSED" || e.event === "TESTS_PASSED",
        );
        blocks.push({
          iteration: iterationNum,
          status: hasPassed ? "PASSED" : "FAILED",
          timestamp: current[0].timestamp,
          events: current,
        });
      }
      iterationNum++;
      current = [entry];
    } else {
      current.push(entry);
    }
  }

  if (current.length > 0) {
    if (iterationNum === 0) iterationNum = 1;
    const hasPassed = current.some(
      (e) =>
        e.event === "CI_PASSED" ||
        e.event === "TESTS_PASSED" ||
        e.event === "COMPLETED",
    );
    blocks.push({
      iteration: iterationNum,
      status: hasPassed ? "PASSED" : "FAILED",
      timestamp: current[0].timestamp,
      events: current,
    });
  }

  return blocks;
}

const EVENT_LABELS: Record<string, string> = {
  CLONE: "Repository cloned",
  BRANCH_CREATED: "Fix branch created",
  TESTS_RUN: "Running tests",
  TESTS_PASSED: "All tests passed",
  TESTS_FAILED: "Tests failed",
  CLASSIFIED_FAILURE: "Failure classified",
  FIX_GENERATED: "Fix generated by LLM",
  FIX_APPLIED: "Patch applied to file",
  COMMITTED: "Changes committed",
  PUSHED: "Pushed to remote",
  CI_MONITORING: "Monitoring CI pipeline",
  CI_PASSED: "CI pipeline passed",
  CI_FAILED: "CI pipeline failed",
  ITERATION_START: "Starting iteration",
  COMPLETED: "Pipeline completed",
  ERROR: "Error occurred",
};

export default function CICDTimeline({
  timeline,
  retryLimit,
}: CICDTimelineProps) {
  const iterations = extractIterations(timeline);
  const totalIterations = iterations.length;

  return (
    <div className="glass-card animate-slide-up space-y-5">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/[0.04]">
            <svg
              className="h-5 w-5 text-brand-400"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={1.5}
                d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
          </div>
          <div>
            <h2 className="text-lg font-semibold text-white">CI/CD Timeline</h2>
            <p className="text-xs text-gray-500">
              Retry loop execution history
            </p>
          </div>
        </div>
        <span className="rounded-full bg-white/[0.04] border border-white/[0.06] px-3 py-1.5 text-sm font-bold text-white tabular-nums">
          {totalIterations}
          <span className="text-gray-500 font-normal">/{retryLimit}</span>
        </span>
      </div>

      {iterations.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-10 text-center">
          <svg
            className="h-10 w-10 text-gray-700"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={1}
              d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"
            />
          </svg>
          <p className="mt-3 text-sm text-gray-500">No iterations recorded</p>
        </div>
      ) : (
        <div className="relative space-y-0">
          {iterations.map((block, idx) => {
            const isPassed = block.status === "PASSED";
            const isLast = idx === iterations.length - 1;

            return (
              <div key={block.iteration} className="relative flex gap-4">
                <div className="flex flex-col items-center">
                  <div
                    className={`relative z-10 flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full border-2 text-sm font-bold ${
                      isPassed
                        ? "border-emerald-500/40 bg-emerald-500/10 text-emerald-400"
                        : "border-red-500/40 bg-red-500/10 text-red-400"
                    }`}
                    style={{
                      boxShadow: isPassed
                        ? "0 0 16px rgba(16,185,129,0.15)"
                        : "0 0 16px rgba(239,68,68,0.15)",
                    }}
                  >
                    {block.iteration}
                  </div>
                  {!isLast && (
                    <div className="w-px flex-1 bg-gradient-to-b from-white/[0.08] to-transparent min-h-[16px]" />
                  )}
                </div>

                <div className="flex-1 pb-6">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="text-sm font-semibold text-white">
                      Iteration {block.iteration}
                    </span>
                    <span
                      className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-0.5 text-[11px] font-bold ${
                        isPassed
                          ? "bg-emerald-500/15 text-emerald-400 border border-emerald-500/25"
                          : "bg-red-500/15 text-red-400 border border-red-500/25"
                      }`}
                    >
                      <span
                        className={`h-1.5 w-1.5 rounded-full ${
                          isPassed ? "bg-emerald-400" : "bg-red-400"
                        }`}
                      />
                      {block.status}
                    </span>
                    <span className="text-[11px] text-gray-600 tabular-nums">
                      {formatDate(block.timestamp)}
                    </span>
                  </div>

                  <div className="mt-2 space-y-1">
                    {block.events
                      .filter((e) => e.event !== "ITERATION_START")
                      .map((entry, eIdx) => (
                        <div
                          key={eIdx}
                          className="flex items-start gap-2 rounded-lg px-3 py-1.5 transition-colors hover:bg-white/[0.02]"
                        >
                          <EventDot event={entry.event} />
                          <div className="min-w-0 flex-1">
                            <span className="text-xs text-gray-400">
                              {EVENT_LABELS[entry.event] ||
                                entry.event.replace(/_/g, " ")}
                            </span>
                            {entry.detail && (
                              <p
                                className="mt-0.5 truncate font-mono text-[11px] text-gray-600"
                                title={entry.detail}
                              >
                                {entry.detail}
                              </p>
                            )}
                          </div>
                          <span className="flex-shrink-0 text-[10px] text-gray-700 tabular-nums">
                            {formatDate(entry.timestamp)}
                          </span>
                        </div>
                      ))}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

function EventDot({ event }: { event: string }) {
  let color = "bg-gray-600";

  if (
    event === "TESTS_PASSED" ||
    event === "CI_PASSED" ||
    event === "COMPLETED"
  ) {
    color = "bg-emerald-500";
  } else if (
    event === "TESTS_FAILED" ||
    event === "CI_FAILED" ||
    event === "ERROR"
  ) {
    color = "bg-red-500";
  } else if (event === "FIX_GENERATED" || event === "FIX_APPLIED") {
    color = "bg-brand-500";
  } else if (event === "CLASSIFIED_FAILURE") {
    color = "bg-yellow-500";
  } else if (event === "COMMITTED" || event === "PUSHED") {
    color = "bg-purple-500";
  }

  return (
    <span
      className={`mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full ${color}`}
    />
  );
}
